# Generated by Django 4.2.30 on 2026-04-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kick_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sessions/thumbnails/'),
        ),
    ]
