# Generated by Django 5.2.11 on 2026-04-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_codes', '0003_accesscode_duration_months_accesscode_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('not_sent', 'Not Sent')], default='not_sent', max_length=20),
        ),
    ]
