# Generated by Django 5.2.11 on 2026-04-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_codes', '0004_accesscode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='shopify_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='shopify_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
