# Generated by Django 4.2.30 on 2026-04-18 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('access_codes', '0005_accesscode_shopify_email_accesscode_shopify_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('weekly', 'Weekly'), ('advanced', 'Advanced')], max_length=20, unique=True)),
                ('product_purchase_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
