# Generated by Django 4.2.30 on 2026-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_tournament_entry_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='product_purchase_link',
        ),
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('basic', 'Basic'), ('weekly', 'Weekly'), ('advanced', 'Advanced')], default='basic', max_length=20),
        ),
    ]
