# Generated by Django 4.2.30 on 2026-04-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_remove_tournament_product_purchase_link_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tournamentparticipation',
            name='tournaments_total_k_c3af39_idx',
        ),
        migrations.AddField(
            model_name='tournamentparticipation',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipation',
            index=models.Index(fields=['-score', '-total_kicks'], name='tournaments_score_f073e9_idx'),
        ),
    ]
