# Generated by Django 4.2.30 on 2026-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_trainingsession_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='participate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='reattempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='video_watched_count',
            field=models.IntegerField(default=0),
        ),
    ]
