# Generated by Django 4.2.30 on 2026-04-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_trainingsession_participate_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcompletion',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='training/completions/videos/'),
        ),
    ]
