# Generated by Django 4.2.30 on 2026-04-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_trainingcompletion_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcompletion',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='training/completions/thumbnails/'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='training/thumbnails/'),
        ),
    ]
